#!/bin/sh

export CAMERA_LIBRARY=opencv
export CONTROL_TURRENT=1
export DO_AIMING=1
export MINIMUM_HUE_TARGET=0
export MAXIMUM_HUE_TARGET=60
export MINIMUM_VALUE_TARGET=0
export MAXIMUM_VALUE_TARGET=255
export STREAMING_SOURCE=0
export FIRING_THREHOLD=15
export DEFAULT_NUDGE=0.04
export CAMERA_OFFSET=175
