---
name: jest action
on:
  pull_request:
  # Run on merge to main because caches are inherited from parent branches
  push:
    branches:
      - main
env:
  NODE_VERSION: "18"
jobs:
  the_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache Node dependencies
        uses: actions/cache@v3
        id: node-cache
        with:
          key: node-${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('poetry.lock') }}
          path: frontend/node_modules
      - name: Install dependencies
        shell: bash
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          npm --prefix ./frontend install ./frontend
      - name: Run tests
        shell: bash
        run: |
          ./test_frontend.sh
